cmake_minimum_required(VERSION 4.1)
include(FetchContent)
FetchContent_Declare(vcpkg URL [[https://github.com/microsoft/vcpkg/archive/refs/tags/2026.04.27.tar.gz]])
FetchContent_MakeAvailable(vcpkg)
set(CMAKE_TOOLCHAIN_FILE "${vcpkg_SOURCE_DIR}/scripts/buildsystems/vcpkg.cmake")
project(ispc_apfrnn LANGUAGES CXX ISPC)
add_executable(ispc_apfrnn main.cpp kernel.ispc)
find_package(TBB CONFIG REQUIRED)
target_link_libraries(ispc_apfrnn PRIVATE TBB::tbb TBB::tbbmalloc TBB::tbbmalloc_proxy)
